- src/views/project/VulListComponent.vue
- src/views/vuln/VulnList.vue
fix:The select option excess length is displayed as a point
> fix:The select option excess length is displayed as a point

- src/views/department/DepartmentList.vue
- src/views/department/types.ts
增加Department接口类型 消除Object的错误类型 规范化tpe
> 增加Department接口类型 消除Object的错误类型 规范化tpe

- src/views/layout/Header.vue
> fix: clear warning

- src/views/layout/Header.vue
Fixed a major bug that could not be started and packaged due to the risk of undefind in some node environments
> Fixed a major bug for TS

- .env
- src/config/lang/en.ts
- src/config/lang/zh_cn.ts
- src/services/deploy.ts
- src/views/sca/ScaList.vue
- vue.config.js
Feature: Add sorting function to SCA list
> Feature: Add sorting function to SCA list

- .env
- src/services/project.ts
- src/services/setting.ts
- src/services/taint.ts
- src/views/setting/components/dangerTable.vue
- src/views/setting/components/hookTable.vue
- src/views/setting/hookRule.vue
- vue.config.js
fix:Issue 248&Feature:issue 255
> fix:Issue 248&Feature:issue 255

- src/views/setting/AgentManage.vue
> fix:HXSecurity/DongTai#329

- src/views/project/ProjectDetail.vue
> fix:HXSecurity/DongTai#333

- src/views/deploy/Deploy.vue
> fix:HXSecurity/DongTai#332

- src/views/taint/searchCard.vue
> fix:searchCard time bug

- nginx.conf
> feature:HXSecurity/DongTai#4

- src/services/setting.ts
- src/views/setting/StrategyManage.vue
- src/views/setting/components/dangerTable.vue
- src/views/setting/components/hookTable.vue
- src/views/setting/sensitive.vue
- src/views/setting/sensitiveManage.vue
feature:HXSecurity/DongTai#348
> feature:HXSecurity/DongTai#348

- src/views/project/ProjectEdit.vue
> [feature]:#135

- src/views/setting/sensitiveManage.vue
fix:Ordinary users can add sensitive information rules
> fix:Ordinary users can add sensitive information rules

- .env
- src/config/lang/en.ts
- src/config/lang/zh_cn.ts
- src/views/sca/ScaDetail.vue
- src/views/sca/ScaList.vue
> feature:#145

- src/config/lang/en.ts
- src/config/lang/zh_cn.ts
- src/views/project/ProjectEdit.vue
- src/views/setting/SysInfo.vue
> feature:issue#143

- package-lock.json
- public/version.txt
- src/assets/about.ts
- src/config/lang/en.ts
- src/config/lang/zh_cn.ts
- src/router/routes.ts
- src/services/setting.ts
- src/views/project/ProjectEdit.vue
- src/views/setting/AgentManage.vue
- src/views/setting/SysInfo.vue
- src/views/setting/about.vue
> feature:#144

- .env
- src/config/lang/en.ts
- src/config/lang/zh_cn.ts
- src/router/routes.ts
- src/views/project/ProjectEdit.vue
- src/views/setting/AgentManage.vue
- src/views/setting/StrategyManage.vue
- src/views/setting/sensitive.vue
- src/views/setting/sensitiveManage.vue
- src/views/setting/templateManage.vue
fix:Adjusted UI details and fixed some detail bugs
> fix:Adjusted UI details and fixed some detail bugs

- src/views/Login.vue
Automatically clear the verification code in case of login error #159
> feature:Automatically clear the verification code in case of login error

- .env
- src/config/lang/en.ts
- src/config/lang/zh_cn.ts
- src/services/deploy.ts
- src/views/deploy/Deploy.vue
- src/views/setting/SysInfo.vue
> update:change php deploy

- src/views/setting/about.vue
> fix:change version

- .env
- .github/dead-link-checker.yaml
- .github/workflows/config/.dlc.json
- package-lock.json
- src/views/project/ProjectDetail.vue
> add dead-link-checker

- .env
- src/config/lang/en.ts
- src/config/lang/zh_cn.ts
- src/views/vuln/VulnDetail.vue
> feature:add hard code

- .env
- src/App.vue
> feature:add discuss

- src/views/setting/components/dangerTable.vue
- src/views/setting/components/hookTable.vue
fixed:Information tips for all operation functions are added
> fixed:Information tips for all operation functions are added

- src/views/sca/ScaList.vue
> feature: scaList add license

- src/config/lang/zh_cn.ts
- src/services/sca.ts
- src/views/project/ProjectDetail.vue
- src/views/sca/ScaDetail.vue
> fixed:cas download

- .env
- src/config/lang/en.ts
- src/config/lang/zh_cn.ts
- src/views/department/userSetting.vue
- src/views/sca/ScaList.vue
> fixed:user resetPassword

- src/config/lang/en.ts
- src/config/lang/zh_cn.ts
- src/views/deploy/Deploy.vue
fixed:Optimized go probe deployment description
> fixed:Optimized go probe deployment description

- src/config/lang/en.ts
- src/config/lang/zh_cn.ts
- src/views/vuln/VulnDetail.vue
fixed:Optimized go probe deployment description
fixed:Fix bug with null vulnerability report export
> Fix bug with null vulnerability report export

- src/views/project/ProjectDetail.vue
fixed:clear thi projectDetail warning
> fixed:clear thi projectDetail warning

- src/views/department/DepartmentList.vue
- src/views/department/userSetting.vue
- src/views/talent/TalentList.vue
> fix：talentList create_time

- src/store/modules/user.ts
- src/views/project/ProjectDetail.vue
> fixed: #193 

- .env
- src/components/G6/Dagre.vue
- src/services/setting.ts
- src/views/setting/about.vue
- vue.config.js
> feature: #187

- src/views/project/ProjectDetail.vue
fixed:There is no change in the interface after modifying the version
> fixed:There is no change in the interface after modifying the version

- src/components/G6/Dagre.vue
fixed:minimap positioning error
> fixed:minimap positioning error

- src/views/setting/LogManage.vue
> fixed:add loading

- .env
- src/services/project.ts
- src/services/vuln.ts
- src/views/project/ProjectDetail.vue
- src/views/project/VulListComponent.vue
- src/views/vuln/VulnList.vue
- vue.config.js
fixed:vulnSummary==>vulnSummary_project;vulnSummary_type
> fixed:vulnSummary==>vulnSummary_project;vulnSummary_type

- src/views/vuln/VulnDetail.vue
fixed:The vulnerability details are still displayed when the URL does not exist
> fixed:The vulnerability details are still displayed when the URL does not exist

- src/views/deploy/Deploy.vue
> fixed:download agent

- src/views/deploy/Deploy.vue
> fixed:AgentDownload

- src/views/project/ProjectDetail.vue
fixed:The height of the chart increases when the version is changed
> fixed:The height of the chart increases when the version is changed

- .env
- src/views/setting/components/dangerTable.vue
- src/views/setting/components/hookTable.vue
- src/views/setting/hookRule.vue
fixed:Rule addition and deletion, rule quantity statistics have not changed
> fixed:Rule addition and deletion, rule quantity statistics have not changed

- .env
- src/views/project/VulListComponent.vue
- src/views/sca/ScaList.vue
- src/views/vuln/VulnList.vue
fixed:The reset button cannot reset the search criteria
> fixed:The reset button cannot reset the search criteria

- src/App.vue
- src/views/department/Index.vue
> fixed:department i18n

- src/components/G6/Dagre.vue
fixed:Eliminate dagre duplicate IDS
> fixed:Eliminate dagre duplicate IDS

- src/config/lang/en.ts
- src/config/lang/zh_cn.ts
- src/views/department/DepartmentList.vue
- src/views/project/ProjectManage.vue
fixed:delete Projuect add confirm
> fixed:delete Projuect add confirm

- src/config/lang/en.ts
- src/config/lang/zh_cn.ts
- src/services/setting.ts
- src/views/setting/agentConfig.vue
> feature:add del agentConfig

- .env
- src/config/lang/en.ts
- src/config/lang/zh_cn.ts
- src/services/setting.ts
- src/views/department/userSetting.vue
- src/views/project/ProjectDetail.vue
- src/views/setting/Index.vue
- src/views/setting/SysInfo.vue
- src/views/setting/agentConfig.vue
- src/views/talent/TalentList.vue
- vue.config.js
feature : complete anentConfig
> feature : complete anentConfig

- src/config/lang/zh_cn.ts
> fixed:remove Confirmed

- .env
- src/views/setting/AgentManage.vue
- src/views/setting/SysInfo.vue
- src/views/setting/agentConfig.vue
> feature:change style

- src/views/setting/agentConfig.vue
> feature: add init config

- src/views/setting/AgentManage.vue
- src/views/setting/SysInfo.vue
- src/views/setting/components/dangerTable.vue
- src/views/setting/components/hookTable.vue
- src/views/setting/scaManage.vue
- src/views/setting/templateManage.vue
> fixed:Beautify page

- src/views/setting/SysInfo.vue
> fixed:agentConfig Auth

- .env
- src/services/setting.ts
- src/views/setting/AgentManage.vue
- src/views/taint/searchCard.vue
feature:add agentManage settingAll
> feature:add agentManage settingAll

- src/views/setting/AgentManage.vue
- src/views/setting/components/status.vue
[fixed:label error](https://github.com/HXSecurity/DongTai-web/commit/34b49d366942db73acc20f360a15c12a0c75fd1e)
> fixed:label error

- src/views/setting/agentConfig.vue
> fixed:MB==>字节

- .github/workflows/deploy-to-test.yml
> increase retry

- src/views/project/ProjectDetail.vue
- src/views/project/components/distribution.vue
> fix select bug

- src/views/project/ProjectDetail.vue
> fixed:change project id bug page not chage

- src/views/project/ProjectDetail.vue
> fix projectDetail background

- src/views/setting/AgentManage.vue
> add agent update

- src/views/project/ProjectEdit.vue
> change project edit page

- src/views/vuln/VulnDetail.vue
Fixed the bug where the call chain propagates duplicate additions
> Fixed the bug where the call chain propagates duplicate additions

- src/views/setting/AgentManage.vue
> ids => agent_ids

- src/views/setting/AgentManage.vue
> change update icon

- src/views/sca/ScaDetail.vue
> fixed:sca time bug

- src/views/vuln/VulnList.vue
> hidden 'discovery time'

- src/views/sca/ScaList.vue
- src/views/setting/AgentManage.vue
> agent and scaList bug fix

- src/views/project/ProjectDetail.vue
- src/views/sca/ScaList.vue
> fixed:change version bug

- src/views/sca/ScaList.vue
> clear first number
